spring:
  application:
    name: taco-cloud
  datasource:
    url: jdbc:h2:mem:tacocloud;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    generate-unique-name: false
    name: tacocloud